apiVersion: v1
kind: Service
metadata:
  name: {{ include "msproductcatalog.fullname" . }}
  labels:
    {{- include "msproductcatalog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "msproductcatalog.selectorLabels" . | nindent 4 }}
