apiVersion: v1
kind: Service
metadata:
  name: {{ include "msrecommendation.fullname" . }}
  labels:
    {{- include "msrecommendation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "msrecommendation.selectorLabels" . | nindent 4 }}
